import { Redis } from '@upstash/redis';

const redis = Redis.fromEnv();

export default async function handler(req, res) {
  const { prompt, email, action, filePath, fileDescription, existingFiles, byok } = req.body;
  if (!email) return res.status(400).json({ error: 'Email required' });
  
  // Credit check only if not BYOK and not file-level call
  if (!byok?.key && action!== 'file') {
    const estimatedCost = Math.max(15, Math.min(50, Math.ceil(prompt.length / 30))); // Higher for multi-file
    const creditCheck = await fetch(`${process.env.VERCEL_URL}/api/check-credits`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, action: 'check', buildCost: estimatedCost })
    }).then(r => r.json());
    
    if (!creditCheck.canBuild) {
      return res.status(402).json({
        error: 'INSUFFICIENT_CREDITS',
        message: `This project needs ~${estimatedCost} credits. You have ${creditCheck.credits}.`,
        tier: creditCheck.tier,
        credits: creditCheck.credits,
        upgrade: true
      });
    }
    
    await fetch(`${process.env.VERCEL_URL}/api/check-credits`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, action: 'deduct', buildCost: estimatedCost })
    });
  }
  
  try {
    // STEP 1: PLAN - Return file structure
    if (action === 'plan') {
      // TODO: Replace with your actual AI call to plan the project
      // Example: Ask GPT-4 "List files needed for: {prompt}. Return JSON: {projectName, files:[{path,description}]}"
      const isReact = prompt.toLowerCase().includes('react');
      const isTodo = prompt.toLowerCase().includes('todo');
      
      const files = isReact? [
        { path: 'index.html', description: 'HTML entry point with React CDN' },
        { path: 'App.jsx', description: 'Main React component with state logic' },
        { path: 'index.css', description: 'Tailwind + custom styles' }
      ] : [
        { path: 'index.html', description: 'Main HTML structure' },
        { path: 'style.css', description: 'CSS styling' },
        { path: 'script.js', description: 'JavaScript app logic' }
      ];
      
      return res.json({ 
        success: true, 
        projectName: isTodo? 'TodoApp' : 'MyApp',
        files 
      });
    }
    
    // STEP 2: FILE - Generate individual file
    if (action === 'file') {
      // TODO: Replace with your actual AI call per file
      // Use byok.key if present, else use your default API key
      // Prompt: "Write {filePath} for this app: {prompt}. Description: {fileDescription}. Existing files: {existingFiles}"
      
      let code = `// ${filePath}\n// ${fileDescription}\n\n`;
      
      if (filePath === 'index.html') {
        code += `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated App</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="style.css">
</head>
<body class="bg-gray-900 text-white">
  <div id="root" class="p-8">
    <h1 class="text-3xl font-bold mb-4">App Generated by Forge</h1>
    <p>Prompt: ${prompt}</p>
  </div>
  <script src="script.js"></script>
</body>
</html>`;
      } else if (filePath === 'App.jsx') {
        code += `function App() {
  const [count, setCount] = React.useState(0);
  return (
    <div className="p-8 bg-gray-900 text-white min-h-screen">
      <h1 className="text-3xl font-bold mb-4">React App</h1>
      <p className="mb-4">Prompt: ${prompt}</p>
      <button 
        onClick={() => setCount(count + 1)}
        className="bg-blue-600 px-4 py-2 rounded"
      >
        Count: {count}
      </button>
    </div>
  );
}`;
      } else if (filePath.includes('.css')) {
        code += `body { 
  font-family: -apple-system, sans-serif; 
  background: #0a0a0a; 
  color: #fff; 
  margin: 0;
  padding: 20px;
}`;
      } else if (filePath.includes('.js')) {
        code += `console.log('App initialized: ${prompt}');
document.addEventListener('DOMContentLoaded', () => {
  console.log('DOM ready');
});`;
      }
      
      return res.json({ success: true, code });
    }
    
    res.status(400).json({ error: 'Invalid action' });
  } catch (err) {
    res.status(500).json({ error: 'Generation failed: ' + err.message });
  }
}
